name : Compila y genera PDF

on: push

jobs:
  compila:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout a la rama
        uses: actions/checkout@v4.2.2
      - name: Compilar el proyecto
        uses: actions/setup-dotnet@v3.4.2
        with: 
          dotnet-version: '9.0.x'
      - name: Instalar dependencias
        run: dotnet restore
      - name: Compilar
        run: dotnet build --no-restore

  crear-PDF:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: docs
          output_dir: pdfs
      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: pdfs
      
